<?php
// api/admin/import_voters.php
require_once __DIR__ . '/../../config/constants.php';
require_once __DIR__ . '/../../config/db_connect.php';
require_once __DIR__ . '/../../helpers/functions.php';
require_once APP_ROOT . '/includes/ActivityLogger.php';

if (session_status() === PHP_SESSION_NONE) session_start();

// Set JSON header
header('Content-Type: application/json');

// Validate admin
if (empty($_SESSION['is_admin']) || $_SESSION['is_admin'] !== true) {
    echo json_encode(['success' => false, 'message' => 'Forbidden']);
    exit;
}

// Validate CSRF token
$reqToken = $_POST['csrf_token'] ?? '';
if (empty($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $reqToken)) {
    echo json_encode(['success' => false, 'message' => 'Invalid CSRF token']);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Method not allowed']);
    exit;
}

if (empty($_FILES['voter_file']) || $_FILES['voter_file']['error'] !== UPLOAD_ERR_OK) {
    echo json_encode(['success' => false, 'message' => 'No file uploaded']);
    exit;
}

$path = $_FILES['voter_file']['tmp_name'];
$handle = fopen($path, 'r');
if (!$handle) {
    echo json_encode(['success' => false, 'message' => 'Cannot open file']);
    exit;
}

try {
    $db = Database::getInstance()->getConnection();
    $logger = new ActivityLogger($db);
    
    $db->beginTransaction();
    
    $inserted = 0;
    $skipped = 0;
    $failed = [];
    $graduationYearsSet = 0;
    $autoGenerated = 0;
    $autoPasswords = 0;
    $generatedPasswords = []; // Store generated passwords to display (for first few)
    $rowNumber = 0;

    // Check if the MySQL function exists - but don't throw error if it doesn't
    $useMySQLFunction = false;
    try {
        $checkFunction = $db->query("SHOW FUNCTION STATUS WHERE Db = DATABASE() AND Name = 'generate_student_id'");
        $useMySQLFunction = ($checkFunction->rowCount() > 0);
        
        if (!$useMySQLFunction) {
            error_log("generate_student_id function not found - using PHP fallback");
        }
    } catch (Exception $e) {
        error_log("Error checking function: " . $e->getMessage());
        $useMySQLFunction = false;
    }

    // Read CSV line by line
    while (($row = fgetcsv($handle)) !== false) {
        $rowNumber++;
        
        // Skip header row if it's the first row and looks like headers
        if ($rowNumber === 1) {
            $firstCell = strtolower(trim($row[0] ?? ''));
            if (in_array($firstCell, ['id', 'student id', 'studentid', 'student_id'])) {
                continue; // Skip header row
            }
        }
        
        // Expected columns: 
        // [ID or *], First Name, Last Name, Department, Level, Email, Entry Year, Graduation Year (optional)
        
        if (count($row) < 7) { 
            $skipped++; 
            $failed[] = "Row $rowNumber: Insufficient columns (" . count($row) . " found, need at least 7)";
            continue; 
        }
        
        // Pad array to ensure we have at least 8 elements
        $row = array_pad(array_map('trim', $row), 8, '');
        
        [$providedId, $first, $last, $dept, $level, $email, $entryYear, $graduationYear] = $row;
        
        // Validate required fields
        if (empty($first) || empty($last) || empty($dept) || empty($level) || empty($email) || empty($entryYear)) { 
            $skipped++; 
            $failed[] = "Row $rowNumber: Missing required fields (first name, last name, department, level, email, entry year)";
            continue; 
        }
        
        // Validate email format
        if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $skipped++;
            $failed[] = "Row $rowNumber: Invalid email format: $email";
            continue;
        }

        // Validate entry year
        if (!preg_match('/^\d{4}$/', $entryYear)) {
            $skipped++;
            $failed[] = "Row $rowNumber: Invalid entry year format (use YYYY): $entryYear";
            continue;
        }
        $entryYearInt = (int)$entryYear;
        $currentYear = (int)date('Y');
        if ($entryYearInt < 2020 || $entryYearInt > $currentYear + 1) {
            $skipped++;
            $failed[] = "Row $rowNumber: Entry year must be between 2020 and " . ($currentYear + 1) . ": $entryYear";
            continue;
        }

        // Validate level format
        $validLevelPattern = '/^[1-6][A-Z]([0-9DHV]{1,2}|G[1-2])$/i';
        if (!preg_match($validLevelPattern, $level)) {
            $skipped++;
            $failed[] = "Row $rowNumber: Invalid level format: $level (must be like 1A1, 2B2, 3DH1, 4DV2, 1AG1, 2AG1, etc.)";
            continue;
        }
        
        // Validate graduation year if provided
        $gradYear = null;
        if (!empty($graduationYear)) {
            if (!preg_match('/^\d{4}$/', $graduationYear)) {
                $skipped++;
                $failed[] = "Row $rowNumber: Invalid graduation year format (use YYYY): $graduationYear";
                continue;
            }
            $year = (int)$graduationYear;
            if ($year < $currentYear || $year > $currentYear + 10) {
                $skipped++;
                $failed[] = "Row $rowNumber: Graduation year must be between $currentYear and " . ($currentYear + 10) . ": $graduationYear";
                continue;
            }
            $gradYear = $year;
        }

        // Determine ID (auto-generate if not provided or if provided as '*')
        $finalId = '';
        if (empty($providedId) || $providedId === '*' || $providedId === 'AUTO') {
            // Auto-generate ID - use MySQL function if available, otherwise PHP fallback
            if ($useMySQLFunction) {
                try {
                    $idStmt = $db->prepare("SELECT generate_student_id(?, ?) as new_id");
                    $idStmt->execute([$dept, $entryYearInt]);
                    $result = $idStmt->fetch(PDO::FETCH_ASSOC);
                    $finalId = $result['new_id'] ?? null;
                } catch (Exception $e) {
                    error_log("MySQL function failed, using PHP fallback: " . $e->getMessage());
                    $finalId = null;
                }
            }
            
            // If MySQL function failed or not available, use PHP fallback
            if (empty($finalId)) {
                $finalId = generateStudentIdPHP($db, $dept, $entryYearInt);
            }
            
            $autoGenerated++;
        } else {
            // Use provided ID, but validate format
            if (!preg_match('/^[A-Z]{3}[0-9]{2}[0-9]{4}$/', $providedId)) {
                $skipped++;
                $failed[] = "Row $rowNumber: Invalid ID format. Must be 3 letters + 6 digits (e.g., GSC250001). Provided: $providedId";
                continue;
            }
            
            // Check if ID already exists
            $exists = $db->prepare("SELECT 1 FROM users WHERE id = ? LIMIT 1");
            $exists->execute([$providedId]);
            if ($exists->fetch()) { 
                $skipped++; 
                $failed[] = "Row $rowNumber: Duplicate student ID: $providedId";
                continue; 
            }
            
            $finalId = $providedId;
        }

        if (empty($finalId)) {
            $skipped++;
            $failed[] = "Row $rowNumber: Failed to generate ID for $first $last";
            continue;
        }

        // AUTO-GENERATE SIMPLE 8-CHARACTER PASSWORD for each user
        $password = generateSimplePassword($first, $last, $finalId);
        $autoPasswords++;
        
        // Store first few generated passwords for display in response
        if ($autoPasswords <= 5) {
            $generatedPasswords[] = [
                'id' => $finalId,
                'name' => $first . ' ' . $last,
                'password' => $password
            ];
        }
        
        $hashed = password_hash($password, PASSWORD_BCRYPT);

        // Insert new voter
        try {
            $stmt = $db->prepare("
                INSERT INTO users 
                (id, password, first_name, last_name, department, level, email, entry_year, graduation_year, has_voted, has_logged_in, is_admin) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 0, 0)
            ");
            
            $stmt->execute([
                $finalId,
                $hashed,
                $first,
                $last,
                $dept,
                $level,
                $email,
                $entryYearInt,
                $gradYear
            ]);
            
            $inserted++;
            if ($gradYear) {
                $graduationYearsSet++;
            }
            
        } catch (Exception $e) {
            $skipped++;
            $failed[] = "Row $rowNumber: Error inserting $finalId: " . $e->getMessage();
        }
    }

    $db->commit();
    fclose($handle);

    // Log the import activity
    if (isset($logger) && $logger) {
        $logger->logActivity(
            $_SESSION['user_id'] ?? 'ADM0001',
            ($_SESSION['first_name'] ?? 'System') . ' ' . ($_SESSION['last_name'] ?? 'Administrator'),
            'import_voters',
            "Imported {$inserted} voters via CSV ({$autoGenerated} auto-generated IDs, {$autoPasswords} auto-generated passwords)",
            [
                'inserted' => $inserted,
                'skipped' => $skipped,
                'auto_generated_ids' => $autoGenerated,
                'auto_generated_passwords' => $autoPasswords,
                'failed_count' => count($failed),
                'graduation_years_set' => $graduationYearsSet
            ]
        );
    }

    // Build response message
    $message = "✅ Imported: {$inserted} voters";
    $message .= " | 🆔 Auto IDs: {$autoGenerated}";
    $message .= " | 🔑 Auto passwords: {$autoPasswords}";
    $message .= " | ⏭️ Skipped: {$skipped}";
    if ($graduationYearsSet > 0) {
        $message .= " | 🎓 Grad years set: {$graduationYearsSet}";
    }

    // Prepare response
    $response = [
        'success' => true,
        'inserted' => $inserted,
        'skipped' => $skipped,
        'auto_generated_ids' => $autoGenerated,
        'auto_generated_passwords' => $autoPasswords,
        'failed' => $failed,
        'graduation_years_set' => $graduationYearsSet,
        'message' => $message
    ];
    
    // Include sample generated passwords in response (first 5)
    if (!empty($generatedPasswords)) {
        $response['sample_passwords'] = $generatedPasswords;
        $response['warning'] = 'Please save these passwords - they are hashed and cannot be retrieved later!';
    }
    
    echo json_encode($response);
    
} catch (Exception $e) {
    // Rollback transaction on error
    if (isset($db)) {
        $db->rollBack();
    }
    if (isset($handle) && $handle) {
        fclose($handle);
    }
    
    error_log("Import voters error: " . $e->getMessage());
    echo json_encode([
        'success' => false,
        'message' => 'Import failed: ' . $e->getMessage()
    ]);
}
exit;

/**
 * PHP fallback function to generate student ID
 * Format: [DEPT-CODE][YEAR-LAST-2][4-DIGIT-SEQUENCE]
 * Example: GSC230001
 */
function generateStudentIdPHP($db, $department, $entryYear) {
    // Department to code mapping
    $deptCodes = [
        'General Science' => 'GSC',
        'General Arts' => 'GAR',
        'Business' => 'BUS',
        'Home Economics' => 'HEC',
        'Visual Arts' => 'VAR',
        'Technical' => 'TEC',
        'Agriculture' => 'AGR',
        'Vocational' => 'VOC'
    ];
    
    // Try to match department name (case-insensitive)
    $deptCode = null;
    $departmentLower = strtolower(trim($department));
    
    foreach ($deptCodes as $deptName => $code) {
        if (strpos($departmentLower, strtolower($deptName)) !== false || 
            strpos(strtolower($deptName), $departmentLower) !== false) {
            $deptCode = $code;
            break;
        }
    }
    
    // Default to first 3 letters uppercase if no match
    if (!$deptCode) {
        $deptCode = strtoupper(substr(preg_replace('/[^a-zA-Z]/', '', $department), 0, 3));
        if (strlen($deptCode) < 3) {
            $deptCode = str_pad($deptCode, 3, 'X');
        }
    }
    
    // Get last 2 digits of entry year
    $yearCode = substr($entryYear, -2);
    
    // Find the next available sequence number
    $pattern = $deptCode . $yearCode . '%';
    
    $stmt = $db->prepare("
        SELECT MAX(CAST(RIGHT(id, 4) AS UNSIGNED)) as max_sequence
        FROM users 
        WHERE id LIKE ? AND LENGTH(id) = 9
    ");
    $stmt->execute([$pattern]);
    $result = $stmt->fetch(PDO::FETCH_ASSOC);
    
    $nextSequence = ($result['max_sequence'] ?? 0) + 1;
    
    // Format with leading zeros (4 digits)
    $sequencePadded = str_pad($nextSequence, 4, '0', STR_PAD_LEFT);
    
    return $deptCode . $yearCode . $sequencePadded;
}
?>